### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Withersip** [samedifferent/morevillagers#20]
## Bug Report:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 30/7/21, 1:12 pm
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'morevillagers-fabric'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3853
		at net.fabricmc.fabric.impl.object.builder.TradeOfferInternals.registerVillagerOffers(TradeOfferInternals.java:43)
		at net.fabricmc.fabric.api.object.builder.v1.trade.TradeOfferHelper.registerVillagerOffers(TradeOfferHelper.java:46)
		at com.telepathicgrunt.repurposedstructures.misc.MobMapTrades.addMapTrades(MobMapTrades.java:17)
		at com.telepathicgrunt.repurposedstructures.RepurposedStructures.onInitialize(RepurposedStructures.java:99)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3853
		at svenhjol.charm.helper.VillagerHelper.addProfession(VillagerHelper.java:30)
		at svenhjol.charm.module.beekeepers.Beekeepers.runWhenEnabled(Beekeepers.java:28)
		at svenhjol.charm.loader.ModuleLoader.lambda$run$3(ModuleLoader.java:70)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
		at svenhjol.charm.loader.ModuleLoader.run(ModuleLoader.java:68)
		at svenhjol.charm.loader.CommonLoader.run(CommonLoader.java:42)
		at svenhjol.charm.loader.ModuleLoader.init(ModuleLoader.java:37)
		at svenhjol.charm.Charm.initCharm(Charm.java:36)
		at svenhjol.charm.Charm.onInitialize(Charm.java:18)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3853
		at net.fabricmc.fabric.impl.object.builder.TradeOfferInternals.registerVillagerOffers(TradeOfferInternals.java:43)
		at net.fabricmc.fabric.api.object.builder.v1.trade.TradeOfferHelper.registerVillagerOffers(TradeOfferHelper.java:46)
		at me.thonk.croptopia.CroptopiaVillagerTrades.init(CroptopiaVillagerTrades.java:18)
		at me.thonk.croptopia.Croptopia.onInitialize(Croptopia.java:94)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3853
		at net.fabricmc.fabric.impl.object.builder.TradeOfferInternals.registerVillagerOffers(TradeOfferInternals.java:43)
		at net.fabricmc.fabric.api.object.builder.v1.trade.TradeOfferHelper.registerVillagerOffers(TradeOfferHelper.java:46)
		at com.slomaxonical.architectspalette.core.registry.APTrades.registerVillagerTrades(APTrades.java:17)
		at com.slomaxonical.architectspalette.core.ArchitectsPalette.onInitialize(ArchitectsPalette.java:25)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
Caused by: java.lang.ExceptionInInitializerError
	at io.github.pheonixvx.morevillagersfabric.init.VillagerInit.fillTradeData(VillagerInit.java:40)
	at io.github.pheonixvx.morevillagersfabric.MoreVillagersFabric.onInitialize(MoreVillagersFabric.java:60)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.NullPointerException: Cannot read field "identifier" because "net.hyper_pigeon.better_wandering_trader.BetterWanderingTraderMod.CONFIG.invisibleTradeFactory.array[<local1>]" is null
	at net.minecraft.class_3853.<clinit>(class_3853.java:527)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$bka000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:47)
	at net.minecraft.class_128.method_560(class_128.java:341)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 461567688 bytes (440 MiB) / 838860800 bytes (800 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel HD Graphics 4000
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x0166
	Graphics card #0 versionInfo: Revision ID: 0x0009
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 5120.00
	Virtual memory used (MB): 3492.90
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 306.25
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalbars: Additional Bars 2.1.1
		adorn: Adorn 2.0.0+1.17
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.2.9
		amecsapi: Amecs API 1.1.5+mc21w16a
		aqupd: Caracal mob 1.17-1.2.2
		aqupdgrizzly: Grizzly Bear mob 1.1.1
		arcana2plus: Arcana ++ 0.0.4+1.17-alpha
		arcanaflavor: Arcana Flavor 0.1.0+1.17
		architects_palette: Architect's Palette Fabric 1.2
		architectury: Architectury 2.2.21
		artifality: Artifality 0.3.3
		assembly: Assembly 21w06a-1.0.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axolotlitemfix: Axolotl Item Fix 1.1.1
		backslot: BackSlot 1.2.0
		backslotaddon: BackSlot Addon 1.0.5
		bclib: BCLib 0.2.4
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterend: Better End 0.10.5-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1
		betterthirdperson: Better Third Person 1.5.0
		biome_locator: Biome Locator 1.1.3
		biomeinfo: Biome Info 1.17-7
		biomepicker: Biome Picker 1.1.1
		caelus: Caelus API 0.0.16-1.17
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.0
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps fabric-1.17.1-7.0.4
		colytra: Colytra 2.0.0-1.17
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.4-1.17
		connected-doors: Connected Doors 1.1+1.17
		consistency_plus: Consistency Plus 0.3.3-build.261_UNMINIFIED
		controlling: Controlling For Fabric 1.1.2
		croptopia: Croptopia 1.5.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customizableelytra-fabric: Customizableelytra Fabric 1.4.0-1.17
		customportalapi: Custom Portals 0.0.1-beta33-1.17
		customstars: Custom Stars 0.5
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		darkpaintings: Dark Paintings 3.0.5
		dawn: Dawn API 2.0.4
		deepslatecutting: Deepslate Cutting 1.1.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dragonloot: DragonLoot 1.0.8
		dual_riders: DualRiders 1.0.5
		earthtojavamobs: Earth2Java 1.7.1+1.17
		elytratrinket: Elytra Trinket 2.0.1-1.17
		emerald_tools: Emerald Tools 1.2.24
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
		enhanced_mushrooms: Enhanced Mushrooms 1.0.5
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabric-tree-chopper: Fabric Tree Chopper 0.7.0
		fabricloader: Fabric Loader 0.11.6
		fabricshieldlib: Fabric Shield Lib 1.3.5-21w05b
		fallingleaves: Falling Leaves 1.7.2+1.17
		fancymenu: FancyMenu 2.2.0
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		flesh2leather: Flesh2Leather 1.0.2
		flytre_lib: FlytreLib 0.2.21
		forgottenrecipes: Forgotten Recipes 1.0.1
		geckolib3: Geckolib 3.0.11
		grass_pass: Grass Bypass 1.0.0
		inmis: Inmis 2.3.1-1.17
		inventoryhud: Inventory HUD + 3.3.2
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		konkrete: Konkrete 1.2.2
		krypton: Krypton 0.1.3
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lovely_snails: Lovely Snails 1.0.2+1.17
		mavm: More Axolotl Variants Mod 1.0.2b
		maybe-data: Maybe data 1.0.1-1.17
		megane: megane 5.1.1
		megane-base: megane-base 5.1.1
		megane-runtime: megane-runtime 5.1.1
		megane-vanilla: megane-vanilla 5.1.1+1.17.1
		minecraft: Minecraft 1.17
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.4
		morerespawnanchors: More Respawn Anchors 1.0.1
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17-rc1
		nears: Nears 1.1.0
		netherite_items: Netherite Items 1.1.0
		notforgotten: Not Forgotten 1.0.0
		npcvariety: NPC Variety 2.1.2
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-2
		optifabric: OptiFabric 1.11.18
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		outvoted: Outvoted 2.0.0-alpha.9
		oxidizelib: OxidizeLib 1.1.0
		patchouli: Patchouli 1.17-54-FABRIC
		paxi: Paxi 1.17-1.2
		pigsteel: Pigsteel Mod 1.6.5
		pugh_tools: Pugh Tools ${version}
		quartzelv: Quartz Elevator 1.2.5
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.1.2+1.17.1
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		scorch: Scorch 1.0.2
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		shulkerutils: shulkerutils 1.0.1-1.17
		snowundertrees: Snow Under Trees 1.0.0
		somnus: Somnus API 0.0.12-1.17
		spark: spark 1.6.1
		spirit: Spirit 1.0.5
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		the_aether: The Aether 1.17.1-1.5.0
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.0
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		tweed: Tweed 3.0.0-beta.26
		universal_ores: Universal Ores 1.0
		untitledduckmod: Untitled Duck Mod 0.3.0
		upgradedechests: Upgraded Ender Chests 1.0.2-1.17
		upgradedshulkers: Upgraded Shulkers 1.0.1-1.17
		urns: Urns 1.0.1
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		veinmining: Vein Mining 0.0.10-1.17
		villagernames: Villager Names 2.0.0
		villagershats: Goosik's Villager Hats 1.2.0
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.0.2
		witherite: Witherite 0.0.8-hotfix
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
		xp_storage: XP Storage 1.4.2+1.17.1
		yungsapi: YUNG's API 1.17-Fabric-13
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.17_HD_U_G9_pre26
	OptiFine Build: 20210709-184608
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17
	OptiFine jar version: OptiFine_1.17_HD_U_G9_pre26
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: /Users/phoebemcfadgen/Library/Application Support/minecraft/.optifine/OptiFine_1.17_HD_U_G9_pre26/Optifine-mapped.jar
	OptiFabric error: <None>

### What's the issue you encountered?
Game crashes on startup with the mod in the mod folder, im not sure if another mod is clashing with it or not. I was
 just starting up minecraft like normal, started minecraft up plenty of times before this with the same mods (including morevillagers) with no crashes, it just randomly started to crash

### How can the issue be reproduced?
I guess just starting minecraft via the fabric launcher with all the same mods installed (bottom of crash log)

### Mod Version
MoreVillagersFabric 2.0.4-SNAPSHOT

### Images, Videos, or Logs
i dont necessarily have any, i dont even know if this is morevillagers it just said  "Could not execute entrypoint stage 'main' due to errors, provided by 'morevillagers-fabric'!" so i assumed it was this mod that caused it. 

Thank you have a good day

**Comment by Withersip** [comment]
also should mention this happens with all other 1.17 versions (as far as im aware, not sure if i tried ALL of them but most)
