### ISSUE TITLE
Crashed while trying to start up MC after downloading the new more villagers mod version snapshot 2.0.5

### ISSUE THREAD

**Issue by dandaifuku** [samedifferent/morevillagers#26]
## Bug Report

[Game crashed after clicking play on the Minecraft launcher. Here's the crash report-
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 8/21/21, 12:34 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'morevillagers-fabric'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NullPointerException: Cannot invoke "io.github.pheonixvx.morevillagersfabric.config.MoreVillagersConfig.saveConfig(java.io.File)" because "config" is null
	at io.github.pheonixvx.morevillagersfabric.config.MoreVillagersConfig.loadConfig(MoreVillagersConfig.java:36)
	at io.github.pheonixvx.morevillagersfabric.MoreVillagersFabric.onInitialize(MoreVillagersFabric.java:30)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$bnh000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details: N/A]

### What's the issue you encountered?

[Just tried starting up minecraft with the new update]

### How can the issue be reproduced?

[ Include a detailed step-by-step process for recreating your issue with only More Villagers installed. ]

### Mod Version

[morevillagers-fabric: MoreVillagersFabric 2.0.5-SNAPSHOT]

### Images, Videos, or Logs

[I was using around 200 mods but the morevillagers-FABRIC-1.17-2.0.4.jar version worked]

**Comment by samedifferent** [comment]
Please use 2.0.4 until we fix the issue.

**Comment by samedifferent** [comment]
Issue has been fixed
