### ISSUE TITLE
Server startup fails likely due to empty config file (2.0.5)

### ISSUE THREAD

**Issue by Telezart** [samedifferent/morevillagers#27]
## Bug Report

(Edit - 2.05 - NOT 2.0.4)

Server startup fails likely due to empty config file (2.0.5)

### What's the issue you encountered?

I am having trouble starting up my server after the last update (2.0.5). It seems the startup process is trying to refer to something in the config file which is empty. I noticed that the previous version of this mod did not have a config file so it must be new.

The server starts up normally again as soon as I remove the config file. 

### How can the issue be reproduced?

Install 2.0.5 of the mod on the server and start it up. Will work because the config file has not been created yet. Start it up again (or start up from backup created after the first run) and the problem may be encountered.

### Mod Version

(2.0.4)

### Images, Videos, or Logs

[14:42:06] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'morevillagers-fabric'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.github.pheonixvx.morevillagersfabric.config.MoreVillagersConfig.saveConfig(java.io.File)" because "config" is null
	at io.github.pheonixvx.morevillagersfabric.config.MoreVillagersConfig.loadConfig(MoreVillagersConfig.java:36) ~[morevillagers-FABRIC-1.17-2.0.5.jar:?]
	at io.github.pheonixvx.morevillagersfabric.MoreVillagersFabric.onInitialize(MoreVillagersFabric.java:30) ~[morevillagers-FABRIC-1.17-2.0.5.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
	... 17 more

**Comment by samedifferent** [comment]
You are not using 2.0.4, you are using 2.0.5, which no longer exists. It was up on CurseForge for less than 30 minutes and then quickly taken down due to this issue. Please use version 2.0.4 in the meantime, as that version is completely stable.

**Comment by Telezart** [comment]
My apologies - I was just realized it was 2.0.5 when I looked in my mod folder and came in to change it. I had noted down what seemed to be the latest version number from the curse forge page so I assumed that was what I was using. Did not realized it had been removed. :)

**Comment by samedifferent** [comment]
Issue has been fixed in the latest version
