### ISSUE TITLE
MalformedJsonException: Couldn't parse data file `morevillagers:all_workstations_get`

### ISSUE THREAD

**Issue by OoLunar** [samedifferent/morevillagers#35]
### What's the issue you encountered?

```log
[22:51:00] [Worker-Main-4/ERROR]: Couldn't parse data file morevillagers:all_workstations_get from morevillagers:advancements/all_workstations_get.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Expected name at line 258 column 6 path $.criteria.huntingpost.conditions
	at net.minecraft.class_3518.method_15267(class_3518.java:495) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_3518.method_15276(class_3518.java:532) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4309.method_20731(class_4309.java:47) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4309.method_18789(class_4309.java:21) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 258 column 6 path $.criteria.huntingpost.conditions
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[gson-2.8.0.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:493) ~[intermediary-1.17.1.jar:?]
	... 11 more
```

### How can the issue be reproduced?

- Install [GDLauncher](https://gdevs.io/)
- Download the [Better Minecraft Fabric Edition](https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric) modpack, from the launcher.
- Update all mods to their latest version. This can be done by right clicking on your fully downloaded Better Minecraft panel, and clicking `Manage`. Go to the `Mods` section, click the three dots in the top left corner by the folder and trash icons, click `Update all mods`.
- Create a new world
- Walk around for awhile until you get disconnected. Chunk generation may be required.

### Mod Version
v2.1.1-SNAPSHOT

### Images, Videos, or Logs
Full log: [latest.log](https://github.com/samedifferent/morevillagers/files/7272705/latest.log)

**Comment by samedifferent** [comment]
This has been fixed in the latest version
