### ISSUE TITLE
[BUG]mod has faild to load correctly

### ISSUE THREAD

**Issue by ZzZzZz112233** [samedifferent/morevillagers#62]
### Mod Version

morevillagers-forge-1.19-4.0.2

### Mod Loader

Forge

### Mod Loader Version

41.0.100

### What happened?

![1](https://user-images.githubusercontent.com/109568541/179657620-a99679d3-caa8-47d3-bef6-5e7ad2387c75.jpg)
can not start the game

### latest.log

[11:16:44] [main/INFO]: ModLauncher running: args [--username, cheng_zi_fly, --version, 1.19, --gameDir, G:\MC1.19\.minecraft, --assetsDir, G:\MC1.19\.minecraft\assets, --assetIndex, 1.19, --uuid, 7abb70d42ece41e2933774f4492cecfc, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, HMCL 3.5.3, --width, 854, --height, 480, --launchTarget, forgeclient, --fml.forgeVersion, 41.0.100, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129]
[11:16:44] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 18.0.1.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[11:16:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/G:/MC1.19/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2390!/ Service=ModLauncher Env=CLIENT
[11:16:44] [main/INFO]: Found mod file morevillagers-forge-1.19-4.0.2.jar of type MOD with provider {mods folder locator at G:\MC1.19\.minecraft\mods}
[11:16:44] [main/WARN]: Mod file G:\MC1.19\.minecraft\libraries\net\minecraftforge\fmlcore\1.19-41.0.100\fmlcore-1.19-41.0.100.jar is missing mods.toml file
[11:16:44] [main/WARN]: Mod file G:\MC1.19\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19-41.0.100\javafmllanguage-1.19-41.0.100.jar is missing mods.toml file
[11:16:44] [main/WARN]: Mod file G:\MC1.19\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19-41.0.100\lowcodelanguage-1.19-41.0.100.jar is missing mods.toml file
[11:16:44] [main/WARN]: Mod file G:\MC1.19\.minecraft\libraries\net\minecraftforge\mclanguage\1.19-41.0.100\mclanguage-1.19-41.0.100.jar is missing mods.toml file
[11:16:44] [main/INFO]: Found mod file fmlcore-1.19-41.0.100.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@408b35bf
[11:16:44] [main/INFO]: Found mod file javafmllanguage-1.19-41.0.100.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@408b35bf
[11:16:44] [main/INFO]: Found mod file lowcodelanguage-1.19-41.0.100.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@408b35bf
[11:16:44] [main/INFO]: Found mod file mclanguage-1.19-41.0.100.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@408b35bf
[11:16:44] [main/INFO]: Found mod file client-1.19-20220607.102129-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@408b35bf
[11:16:44] [main/INFO]: Found mod file forge-1.19-41.0.100-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@408b35bf
[11:16:44] [main/INFO]: No dependencies to load found. Skipping!
[11:16:45] [main/INFO]: Compatibility level set to JAVA_17
[11:16:45] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.19, --gameDir, G:\MC1.19\.minecraft, --assetsDir, G:\MC1.19\.minecraft\assets, --uuid, 7abb70d42ece41e2933774f4492cecfc, --username, cheng_zi_fly, --assetIndex, 1.19, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, HMCL 3.5.3, --width, 854, --height, 480]
[11:16:45] [main/WARN]: Reference map 'morevillagers-forge-forge-refmap.json' for morevillagers.mixins.json could not be read. If this is a development environment you can ignore this message
[11:16:48] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[11:16:49] [Render thread/WARN]: Assets URL 'union:/G:/MC1.19/.minecraft/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23144!/assets/.mcassetsroot' uses unexpected schema
[11:16:49] [Render thread/WARN]: Assets URL 'union:/G:/MC1.19/.minecraft/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23144!/data/.mcassetsroot' uses unexpected schema
[11:16:49] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:16:51] [Render thread/INFO]: Setting user: cheng_zi_fly
[11:16:51] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[11:16:52] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: morevillagers, class com.samebutdifferent.morevillagers.forge.MoreVillagersForge
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.100.jar%23146!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.100.jar%23145!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchFieldError: PROFESSIONS
	at com.samebutdifferent.morevillagers.platform.forge.CommonPlatformHelperImpl.<clinit>(CommonPlatformHelperImpl.java:19) ~[morevillagers-forge-1.19-4.0.2.jar%23143!/:?]
	at com.samebutdifferent.morevillagers.platform.CommonPlatformHelper.registerCreativeModeTab(CommonPlatformHelper.java) ~[morevillagers-forge-1.19-4.0.2.jar%23143!/:?]
	at com.samebutdifferent.morevillagers.MoreVillagers.<clinit>(MoreVillagers.java:21) ~[morevillagers-forge-1.19-4.0.2.jar%23143!/:?]
	at com.samebutdifferent.morevillagers.forge.MoreVillagersForge.<init>(MoreVillagersForge.java:26) ~[morevillagers-forge-1.19-4.0.2.jar%23143!/:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	... 11 more
[11:16:52] [modloading-worker-0/INFO]: Forge mod loading, version 41.0.100, for MC 1.19 with MCP 20220607.102129
[11:16:52] [modloading-worker-0/INFO]: MinecraftForge v41.0.100 Initialized
[11:16:52] [Render thread/FATAL]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Block to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Item to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RenderLevelStageEvent$RegisterStageEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterParticleProvidersEvent to a broken mod state
[11:16:52] [Render thread/INFO]: Narrator library for x64 successfully loaded
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterTextureAtlasSpriteLoadersEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientTooltipComponentFactoriesEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterEntitySpectatorShadersEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterKeyMappingsEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterRecipeBookCategoriesEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterGuiOverlaysEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterDimensionSpecialEffectsEvent to a broken mod state
[11:16:52] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterNamedRenderTypesEvent to a broken mod state
[11:16:52] [Render thread/INFO]: Reloading ResourceManager: Default
[11:16:52] [Worker-Main-17/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterGeometryLoaders to a broken mod state
[11:16:52] [Worker-Main-20/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:52] [Worker-Main-11/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:52] [Worker-Main-12/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:57] [Worker-Main-17/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterAdditional to a broken mod state
[11:16:58] [Worker-Main-17/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:58] [Worker-Main-17/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:58] [Worker-Main-17/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:58] [Worker-Main-17/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:58] [Worker-Main-17/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:58] [Worker-Main-17/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:58] [Worker-Main-17/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:16:58] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[11:16:58] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[11:16:58] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on 扬声器 (USBAudio2.0)
[11:16:58] [Render thread/INFO]: Sound engine started
[11:16:58] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[11:16:58] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:16:59] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:16:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:16:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:16:59] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:16:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:16:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$BakingCompleted to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
[11:16:59] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state
[11:16:59] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:16:59] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:16:59] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[11:16:59] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:17:01] [Render thread/FATAL]: Preparing crash report with UUID aba46789-ae09-4448-8658-40ae594e05d1
[11:17:01] [Render thread/FATAL]: Crash report saved to G:\MC1.19\.minecraft\crash-reports\crash-2022-07-19_11.17.01-fml.txt
[11:17:01] [Render thread/FATAL]: Preparing crash report with UUID d0729cbb-5c1a-4a39-8ba2-372d7f940405

**Comment by samedifferent** [comment]
Use a forge version before 41.0.94

**Comment by nheath** [comment]
Please consider this a request to update to support the newer forge versions?
