### ISSUE TITLE
Issue starting server with more villagers on forge

### ISSUE THREAD

**Issue by campbebj** [samedifferent/morevillagers#8]
## Bug Report

could not start server with more villagers on forge.

### What's the issue you encountered?

could not start server.

### How can the issue be reproduced?

spin up my server.

### Mod Version

1.5.1

### Images, Videos, or Logs

[11Jun2021 13:52:59.718] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Could not initialize class net.minecraft.entity.merchant.villager.VillagerTrades
        Index: 4
        Listeners:
                0: NORMAL
                1: ASM: com.samebutdifferent.morevillagers.MoreVillagers@5b10cb1b onServerAboutToStartEvent(Lnet/minecraftforge/fml/event/server/FMLServerAboutToStartEvent;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda$2578/587256500@353528df
                3: net.minecraftforge.eventbus.EventBus$$Lambda$2578/587256500@72bd6669
                4: net.minecraftforge.eventbus.EventBus$$Lambda$2578/587256500@62fcee2e
                5: net.minecraftforge.eventbus.EventBus$$Lambda$2578/587256500@e57242c
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.entity.merchant.villager.VillagerTrades
        at net.minecraftforge.common.VillagerTradingManager.<clinit>(VillagerTradingManager.java:46)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.lang.Thread.run(Thread.java:748)

**Comment by samedifferent** [comment]
Were you able to reproduce the issue with only More Villagers installed and no other mods?

**Comment by campbebj** [comment]
not a real issue sorry. its a known issue cauesd by https://github.com/TrueGkoliver/FullVillagerEnchants/issues/1 removing it fixed everything. but it causes multiple crashes in other mods.
