### ISSUE TITLE
[Bug]: Incompatible with Villager Names 

### ISSUE THREAD

**Issue by Abisos** [samedifferent/morevillagers#97]
### Mod Version

1.20.1-5.0.0

### Mod Loader

Fabric

### Mod Loader Version

1.20.1

### What happened?

The server crashes.

### latest.log

<html>
<body>

---- Minecraft Crash Report ----
--
2 | // Why is it breaking :(
3 |  
4 | Time: 2023-12-28 23:18:02
5 | Description: Exception ticking world
6 |  
7 | java.lang.NoSuchFieldError: femalenames
8 | at com.natamus.villagernames_common_fabric.util.Names.getRandomName(Names.java:51)
9 | at com.natamus.villagernames_common_fabric.events.VillagerEvent.onSpawn(VillagerEvent.java:41)
10 | at com.natamus.villagernames.ModFabric.lambda$loadEvents$0(ModFabric.java:27)
11 | at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:39)
12 | at net.minecraft.class_3218$class_5526.handler$zie000$fabric-lifecycle-events-v1$invokeEntityLoadEvent(class_3218.java:1696)
13 | at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1577)
14 | at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1536)
15 | at net.minecraft.class_5579.method_31847(class_5579.java:216)
16 | at net.minecraft.class_5579.method_31820(class_5579.java:186)
17 | at net.minecraft.class_5579.method_31857(class_5579.java:351)
18 | at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
19 | at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
20 | at net.minecraft.class_5579.method_31853(class_5579.java:351)
21 | at net.minecraft.class_5579.method_31809(class_5579.java:357)
22 | at net.minecraft.class_3218.method_18765(class_3218.java:394)
23 | at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
24 | at net.minecraft.class_3176.method_3813(class_3176.java:283)
25 | at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
26 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
27 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
28 | at java.base/java.lang.Thread.run(Thread.java:840)
29 |  
30 |  
31 | A detailed walkthrough of the error, its code path and all known details is as follows:
32 | ---------------------------------------------------------------------------------------
33 |  
34 | -- Head --
35 | Thread: Server thread
36 | Stacktrace:
37 | at com.natamus.villagernames_common_fabric.util.Names.getRandomName(Names.java:51)
38 | at com.natamus.villagernames_common_fabric.events.VillagerEvent.onSpawn(VillagerEvent.java:41)
39 | at com.natamus.villagernames.ModFabric.lambda$loadEvents$0(ModFabric.java:27)
40 | at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:39)
41 | at net.minecraft.class_3218$class_5526.handler$zie000$fabric-lifecycle-events-v1$invokeEntityLoadEvent(class_3218.java:1696)
42 | at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1577)
43 | at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1536)
44 | at net.minecraft.class_5579.method_31847(class_5579.java:216)
45 | at net.minecraft.class_5579.method_31820(class_5579.java:186)
46 | at net.minecraft.class_5579.method_31857(class_5579.java:351)
47 | at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
48 | at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
49 | at net.minecraft.class_5579.method_31853(class_5579.java:351)
50 | at net.minecraft.class_5579.method_31809(class_5579.java:357)
51 | at net.minecraft.class_3218.method_18765(class_3218.java:394)

</body>
</html>---- Minecraft Crash Report ----
// Why is it breaking :(

Time: [2](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L2)02[3](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L3)-12-28 23:18:02
Description: Exception ticking world

java.lang.NoSuchFieldError: femalenames
	at com.natamus.villagernames_common_fabric.util.Names.getRandomName(Names.java:51)
	at com.natamus.villagernames_common_fabric.events.VillagerEvent.onSpawn(VillagerEvent.java:[4](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L4)1)
	at com.natamus.villagernames.ModFabric.lambda$loadEvents$0(ModFabric.java:27)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:39)
	at net.minecraft.class_3218$class_[5](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L5)52[6](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L6).handler$zie000$fabric-lifecycle-events-v1$invokeEntityLoadEvent(class_3218.java:1696)
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:15[7](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L7)7)
	at net.minecraft.class_321[8](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L8)$class_5526.method_31798(class_3218.java:1536)
	at net.minecraft.class_5579.method_31847(class_5579.java:216)
	at net.minecraft.class_5579.method_31820(class_5579.java:186)
	at net.minecraft.class_5579.method_31857(class_5579.java:351)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5579.method_31853(class_5579.java:351)
	at net.minecraft.class_5579.method_31809(class_5579.java:357)
	at net.minecraft.class_3218.method_18765(class_3218.java:394)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.natamus.villagernames_common_fabric.util.Names.getRandomName(Names.java:51)
	at com.natamus.villagernames_common_fabric.events.VillagerEvent.onSpawn(VillagerEvent.java:41)
	at com.natamus.villagernames.ModFabric.lambda$loadEvents$0(ModFabric.java:27)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:3[9](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L9))
	at net.minecraft.class_3218$class_5526.handler$zie000$fabric-lifecycle-events-v1$invokeEntityLoadEvent(class_3218.java:1696)
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1577)
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1536)
	at net.minecraft.class_5579.method_31847(class_5579.java:216)
	at net.minecraft.class_5579.method_31820(class_5579.java:186)
	at net.minecraft.class_5579.method_31857(class_5579.java:351)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5579.method_3[18](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L18)53(class_5579.java:351)
	at net.minecraft.class_5579.method_31809(class_5579.java:357)
	at net.minecraft.class_3[21](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L21)8.method_18765(class_[32](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L32)18.java:[39](https://aternos.org/files/crash-reports/crash-2023-12-28_23.18.02-server.txt#L39)4)

**Comment by Abisos** [comment]
Curseforge Project ID:   345854
